# Generated by Django 2.2.28 on 2024-10-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='prefectures',
            new_name='job_prefectures',
        ),
        migrations.RenameField(
            model_name='joboffer',
            old_name='salary',
            new_name='job_salary',
        ),
    ]
